# Generated by Django 6.0.5 on 2026-05-13 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del viaje')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('fecha_regreso', models.DateField(verbose_name='Fecha de regreso')),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por persona (MXN)')),
                ('incluye', models.TextField(blank=True, help_text='Lista de servicios incluidos', verbose_name='¿Qué incluye?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['fecha_salida'],
            },
        ),
    ]
