# Generated by Django 6.0.5 on 2026-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad máxima de viajeros'),
        ),
    ]
