# Generated by Django 6.0.5 on 2026-05-13 05:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
        ('viajes', '0002_viaje_capacidad_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='precio_por_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio base por persona (MXN)'),
        ),
        migrations.CreateModel(
            name='ViajeHabitacionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por persona (MXN)')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoteles.tipohabitacion', verbose_name='Tipo de habitación')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Precio por tipo de habitación',
                'verbose_name_plural': 'Precios por tipo de habitación',
                'unique_together': {('viaje', 'tipo_habitacion')},
            },
        ),
    ]
