# Generated by Django 6.0.5 on 2026-05-13 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_remove_habitacion_precio_por_noche'),
        ('viajes', '0003_alter_viaje_precio_por_persona_viajehabitacionprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio total del viaje (MXN)')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaje_habitaciones', to='hoteles.habitacion', verbose_name='Habitación')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_habitaciones', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Habitación del viaje',
                'verbose_name_plural': 'Habitaciones del viaje',
                'unique_together': {('viaje', 'habitacion')},
            },
        ),
    ]
