# Generated by Django 6.0.5 on 2026-05-13 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_viajehabitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajehabitacion',
            name='precio_frecuente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio viajero frecuente (MXN)'),
        ),
    ]
