# Generated by Django 6.0.5 on 2026-05-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_viajehabitacion_precio_frecuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAbordaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', models.CharField(max_length=200, verbose_name='Punto de abordaje')),
                ('hora_abordaje', models.TimeField(verbose_name='Hora de abordaje')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_abordaje', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Punto de abordaje',
                'verbose_name_plural': 'Puntos de abordaje',
                'ordering': ['hora_abordaje'],
            },
        ),
    ]
