# Generated by Django 6.0.5 on 2026-05-13 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_puntoabordaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='precio_frecuente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio viajero frecuente por persona (MXN)'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio_por_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por persona (MXN)'),
        ),
    ]
