# Generated by Django 6.0.5 on 2026-05-20 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('duracion', models.CharField(help_text='Ej: 1 Día, 2 Días / 1 Noche', max_length=100, verbose_name='Duración')),
                ('lugar_salida', models.TextField(help_text='Un lugar por línea', verbose_name='Lugar de salida')),
                ('inicio_registro', models.CharField(help_text='Ej: 06:30 AM', max_length=50, verbose_name='Inicio de registro')),
                ('hora_salida', models.CharField(help_text='Ej: 07:00 AM', max_length=50, verbose_name='Hora de salida')),
                ('hora_regreso', models.CharField(help_text='Ej: 10:30 PM', max_length=100, verbose_name='Hora / fecha de regreso')),
                ('titulo_descripcion', models.CharField(max_length=200, verbose_name='Título de la descripción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('costo_frecuente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo viajero frecuente')),
                ('incluye', models.TextField(help_text='Un elemento por línea', verbose_name='Incluye')),
                ('no_incluye', models.TextField(help_text='Un elemento por línea', verbose_name='No incluye')),
                ('imagen_principal', models.ImageField(upload_to='tours/principal/', verbose_name='Imagen principal (portada)')),
                ('imagen_index', models.ImageField(upload_to='tours/index/', verbose_name='Imagen para el índice')),
                ('imagen_incluye', models.ImageField(blank=True, upload_to='tours/incluye/', verbose_name='Imagen sección incluye')),
                ('imagen_itinerario', models.ImageField(blank=True, upload_to='tours/itinerario/', verbose_name='Imagen itinerario')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tours/carrusel/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrusel', to='tours.tour')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FechaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de salida')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='tours.tour')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='DiaItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(verbose_name='Día')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título del día')),
                ('actividades', models.TextField(help_text='Una actividad por línea', verbose_name='Actividades')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='tours.tour')),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
    ]
