# Generated by Django 6.0.5 on 2026-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='pdf_info',
            field=models.FileField(blank=True, help_text='Archivo PDF con información del tour', upload_to='tours/pdf/', verbose_name='PDF informativo'),
        ),
    ]
