# Generated by Django 6.0.5 on 2026-05-13 02:25

import django.core.validators
import django.db.models.deletion
import reservaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('hoteles', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteReservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=False, verbose_name='Es titular')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cliente en reservación',
                'verbose_name_plural': 'Clientes en reservación',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=reservaciones.models._generar_codigo, editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('fecha_checkin', models.DateField(verbose_name='Fecha check-in')),
                ('fecha_checkout', models.DateField(verbose_name='Fecha check-out')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('clientes', models.ManyToManyField(through='reservaciones.ClienteReservacion', to='clientes.cliente', verbose_name='Clientes')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='hoteles.habitacion', verbose_name='Habitación')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='viajes.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto (MXN)')),
                ('fecha', models.DateField(verbose_name='Fecha del pago')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('transferencia', 'Transferencia bancaria'), ('paypal', 'PayPal'), ('otro', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='completado', max_length=20, verbose_name='Estado')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia / Comprobante')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservaciones.reservacion', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='clientereservacion',
            name='reservacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_reservacion', to='reservaciones.reservacion'),
        ),
        migrations.AlterUniqueTogether(
            name='clientereservacion',
            unique_together={('reservacion', 'cliente')},
        ),
    ]
