# Generated by Django 6.0.5 on 2026-05-13 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='precio_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se llena, este monto reemplaza el cálculo automático.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio personalizado (MXN)'),
        ),
    ]
