# Generated by Django 6.0.5 on 2026-05-13 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0005_habitacion_nombre_hotel_remove_fk'),
        ('reservaciones', '0002_precio_personalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='hoteles.habitacion', verbose_name='Habitación'),
        ),
    ]
