# Generated by Django 6.0.5 on 2026-05-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='num_camas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de camas'),
        ),
    ]
