# Generated by Django 6.0.5 on 2026-05-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_habitacion_num_camas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='precio_por_noche',
        ),
    ]
