# Generated by Django 6.0.5 on 2026-05-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_remove_habitacion_precio_por_noche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='estrellas',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pais',
        ),
    ]
