# Generated by Django 6.0.5 on 2026-05-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('tipo_documento', models.CharField(choices=[('pasaporte', 'Pasaporte'), ('dni', 'DNI / INE'), ('cedula', 'Cédula'), ('otro', 'Otro')], default='pasaporte', max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
