# Generated by Django 6.0.5 on 2026-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('pasaporte', 'Pasaporte'), ('dni', 'DNI / INE'), ('cedula', 'Cédula'), ('otro', 'Otro')], default='pasaporte', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
