# Generated by Django 6.0.5 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='viajero_frecuente',
            field=models.BooleanField(default=False, verbose_name='Viajero frecuente'),
        ),
    ]
